# Stage 1: Build the Vue application
FROM oven/bun:1.4-alpine AS builder
WORKDIR /app

# Copy package.json and Bun's lockfile (if you have generated one locally)
COPY package.json bun.lock* ./

# Install dependencies using Bun
RUN bun install

COPY . .

# Accept arguments and set as environment variables for Bun
ARG VITE_APP_VERSION=dev
ARG VITE_COMMIT_SHA=none
ARG VITE_BUILD_TIME=unknown
ARG VITE_API_BASE_URL=/api
ARG VITE_LINE_LIFF_ID="__VITE_LINE_LIFF_ID__"
ARG VITE_LINE_URL_OA_BOT="__VITE_LINE_URL_OA_BOT__"

ENV VITE_APP_VERSION=$VITE_APP_VERSION
ENV VITE_COMMIT_SHA=$VITE_COMMIT_SHA
ENV VITE_BUILD_TIME=$VITE_BUILD_TIME
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_LINE_LIFF_ID=$VITE_LINE_LIFF_ID
ENV VITE_LINE_URL_OA_BOT=$VITE_LINE_URL_OA_BOT

# Build the project using Bun
RUN bun run build

# Stage 2: Serve with Nginx and proxy to Go
FROM nginx:1.31-alpine

# Install timezone data
RUN apk add --no-cache tzdata

# Copy the built Vue files to Nginx's default public folder
COPY --from=builder /app/dist /usr/share/nginx/html
# Overwrite the default Nginx config with our custom proxy routing
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]